export const results = [
	{
		"Challenge Problems E": {
			Incorrect: "10",
			Skipped: "0",
			Correct: "2",
			Set: "Challenge Problems E",
		},
		"Ravens Problems D": {
			Incorrect: "8",
			Skipped: "0",
			Correct: "4",
			Set: "Ravens Problems D",
		},
		"Test Problems D": {
			Incorrect: "6",
			Skipped: "0",
			Correct: "6",
			Set: "Test Problems D",
		},
		"Ravens Problems B": {
			Incorrect: "4",
			Skipped: "0",
			Correct: "8",
			Set: "Ravens Problems B",
		},
		"Test Problems B": {
			Incorrect: "5",
			Skipped: "0",
			Correct: "7",
			Set: "Test Problems B",
		},
		"Challenge Problems D": {
			Incorrect: "9",
			Skipped: "0",
			Correct: "3",
			Set: "Challenge Problems D",
		},
		"Test Problems C": {
			Incorrect: "3",
			Skipped: "0",
			Correct: "9",
			Set: "Test Problems C",
		},
		"Basic Problems E": {
			Incorrect: "10",
			Skipped: "0",
			Correct: "2",
			Set: "Basic Problems E",
		},
		"Test Problems E": {
			Incorrect: "9",
			Skipped: "0",
			Correct: "3",
			Set: "Test Problems E",
		},
		"Basic Problems B": {
			Incorrect: "3",
			Skipped: "0",
			Correct: "9",
			Set: "Basic Problems B",
		},
		"Basic Problems C": {
			Incorrect: "3",
			Skipped: "0",
			Correct: "9",
			Set: "Basic Problems C",
		},
		"Ravens Problems E": {
			Incorrect: "10",
			Skipped: "0",
			Correct: "2",
			Set: "Ravens Problems E",
		},
		"Challenge Problems C": {
			Incorrect: "6",
			Skipped: "0",
			Correct: "6",
			Set: "Challenge Problems C",
		},
		"Challenge Problems B": {
			Incorrect: "7",
			Skipped: "0",
			Correct: "5",
			Set: "Challenge Problems B",
		},
		"Basic Problems D": {
			Incorrect: "8",
			Skipped: "0",
			Correct: "4",
			Set: "Basic Problems D",
		},
		"Ravens Problems C": {
			Incorrect: "5",
			Skipped: "0",
			Correct: "7",
			Set: "Ravens Problems C",
		},
	},
	{
		"Challenge Problems E": {
			Incorrect: "9",
			Skipped: "0",
			Correct: "3",
			Set: "Challenge Problems E",
		},
		"Ravens Problems D": {
			Incorrect: "7",
			Skipped: "0",
			Correct: "5",
			Set: "Ravens Problems D",
		},
		"Test Problems D": {
			Incorrect: "7",
			Skipped: "0",
			Correct: "5",
			Set: "Test Problems D",
		},
		"Ravens Problems B": {
			Incorrect: "4",
			Skipped: "0",
			Correct: "8",
			Set: "Ravens Problems B",
		},
		"Test Problems B": {
			Incorrect: "5",
			Skipped: "0",
			Correct: "7",
			Set: "Test Problems B",
		},
		"Challenge Problems D": {
			Incorrect: "8",
			Skipped: "0",
			Correct: "4",
			Set: "Challenge Problems D",
		},
		"Test Problems C": {
			Incorrect: "3",
			Skipped: "0",
			Correct: "9",
			Set: "Test Problems C",
		},
		"Basic Problems E": {
			Incorrect: "8",
			Skipped: "0",
			Correct: "4",
			Set: "Basic Problems E",
		},
		"Test Problems E": {
			Incorrect: "10",
			Skipped: "0",
			Correct: "2",
			Set: "Test Problems E",
		},
		"Basic Problems B": {
			Incorrect: "3",
			Skipped: "0",
			Correct: "9",
			Set: "Basic Problems B",
		},
		"Basic Problems C": {
			Incorrect: "3",
			Skipped: "0",
			Correct: "9",
			Set: "Basic Problems C",
		},
		"Ravens Problems E": {
			Incorrect: "9",
			Skipped: "0",
			Correct: "3",
			Set: "Ravens Problems E",
		},
		"Challenge Problems C": {
			Incorrect: "7",
			Skipped: "0",
			Correct: "5",
			Set: "Challenge Problems C",
		},
		"Challenge Problems B": {
			Incorrect: "7",
			Skipped: "0",
			Correct: "5",
			Set: "Challenge Problems B",
		},
		"Basic Problems D": {
			Incorrect: "7",
			Skipped: "0",
			Correct: "5",
			Set: "Basic Problems D",
		},
		"Ravens Problems C": {
			Incorrect: "6",
			Skipped: "0",
			Correct: "6",
			Set: "Ravens Problems C",
		},
	},
];
